package pt.tecnico.hdlt.T25.server;

/* these imported classes are generated by the hello-world-server contract */
import pt.tecnico.hdlt.T25.Message;
import pt.tecnico.hdlt.T25.MessageServiceGrpc;

import io.grpc.stub.StreamObserver;

import javax.crypto.Cipher;
import javax.crypto.spec.IvParameterSpec;
import javax.crypto.spec.SecretKeySpec;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.security.*;
import java.security.interfaces.RSAPrivateKey;
import java.security.interfaces.RSAPublicKey;
import java.security.spec.PKCS8EncodedKeySpec;
import java.security.spec.X509EncodedKeySpec;
import java.util.Base64;

import static java.nio.charset.StandardCharsets.UTF_8;
import static java.nio.file.Files.readAllBytes;
import static pt.tecnico.hdlt.T25.crypto.Crypto.*;

public class MessageServiceImpl extends MessageServiceGrpc.MessageServiceImplBase {

	@Override
	public void greeting(Message.MessageRequest request, StreamObserver<Message.MessageResponse> responseObserver) {
		String privKeyFileName = "priv.key";
		String pubKeyFileName = "client-pub.key";

		try {
			RSAPublicKey clientPublicKey = getPub(pubKeyFileName);
			RSAPrivateKey serverPrivateKey = getPriv(privKeyFileName);
			Message.MessageResponse response = null;

			String requestContent = request.getContent();
			String requestSignature = request.getSignature();
			String decipheredContent = decryptAES(requestContent);
			if (verify(requestContent, requestSignature, clientPublicKey)) {
				System.out.println("Signature verified! Received message -> " + decipheredContent);
				String content = encryptAES(decipheredContent);
				response = Message.MessageResponse.newBuilder()
						.setContent(content)
						.setSignature(sign(content, serverPrivateKey))
						.build();
			}

			responseObserver.onNext(response);
			responseObserver.onCompleted();
		} catch (Exception ignored) {
			System.out.println("morri");
		}
	}
}
